[project]
name = "example-app"
revision = "1.0"

[secrets.DATABASE_URL]
description = "PostgreSQL connection string"
required = true

[secrets.API_KEY]
description = "API key for external service"
required = true

[secrets.REDIS_URL]
description = "Redis connection for caching"
required = false
default = "redis://localhost:6379"

[secrets.LOG_LEVEL]
description = "Application log level"
required = false
default = "info"

# Profile-specific overrides
[secrets.DATABASE_URL.development]
required = false
default = "sqlite://./dev.db"

[secrets.API_KEY.development]
required = false
default = "dev-api-key-for-testing"