[project]
name = "example-app"
revision = "1.0"

[profiles.default]
DATABASE_URL = { description = "PostgreSQL connection string", required = true }
API_KEY = { description = "API key for external service", required = true }
REDIS_URL = { description = "Redis connection for caching", required = false, default = "redis://localhost:6379" }
LOG_LEVEL = { description = "Application log level", required = false, default = "info" }

[profiles.development]
DATABASE_URL = { description = "PostgreSQL connection string", required = false, default = "sqlite://./dev.db" }
API_KEY = { description = "API key for external service", required = false, default = "dev-api-key-for-testing" }
REDIS_URL = { description = "Redis connection for caching", required = false, default = "redis://localhost:6379" }
LOG_LEVEL = { description = "Application log level", required = false, default = "debug" }

[profiles.production]
DATABASE_URL = { description = "PostgreSQL connection string", required = true }
API_KEY = { description = "API key for external service", required = true }
REDIS_URL = { description = "Redis connection for caching", required = true }
LOG_LEVEL = { description = "Application log level", required = false, default = "info" }