[workspace]
members = [".", "secretspec-derive", "secretspec-types", "examples/codegen_example"]
resolver = "2"

[package]
name = "secretspec"
version = "0.1.0"
edition = "2024"

[lib]
name = "secretspec"
path = "src/lib.rs"

[[bin]]
name = "secretspec"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
keyring = "2.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
thiserror = "1.0"
directories = "5.0"
colored = "2.0"
rpassword = "7.4.0"
dotenvy = "0.15"
inquire = "0.6"
color-eyre = "0.6"
secretspec-derive = { path = "./secretspec-derive", optional = true }
secretspec-types = { path = "./secretspec-types" }
serde_json = "1.0"
tempfile = "3.0"

[features]
default = ["codegen"]
codegen = ["secretspec-derive"]

[dev-dependencies]