[project]
name = "secretspec"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
# API_KEY = { description = "API key for external service", required = true }
# DATABASE_URL = { description = "Database connection string", required = true }

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# API_KEY = { required = false, default = "dev-api-key" }
# DATABASE_URL = { default = "sqlite:///dev.db" }
# JWT_SECRET = { description = "Secret key for JWT token signing", required = true }
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
# EMAIL_PROVIDER = { description = "Email service provider", required = false, default = "console" }
# OAUTH_CLIENT_ID = { description = "OAuth client ID", required = false }
# OAUTH_CLIENT_SECRET = { description = "OAuth client secret", required = false }
