[package]
name = "secretspec-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
secretspec = { path = "..", features = ["codegen"] }

[build-dependencies]
secretspec = { path = "..", features = ["codegen"] }

[dev-dependencies]
tempfile = "3.0"