[package]
name = "derive-example"
version.workspace = true
edition.workspace = true

[dependencies]
secretspec.workspace = true
url.workspace = true
serde.workspace = true

[package.metadata.dist]
dist = false
