name: Publish Crates

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to publish (e.g., 0.1.2 or v0.1.2)"
        required: true
        type: string
  push:
    tags:
      - "*[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish secretspec crate
        run: cargo publish -p secretspec
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Publish secretspec-derive crate
        run: cargo publish -p secretspec-derive
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
